config/routes.rb
Rails.application.routes.draw do
  #get 'employees/index'
  #get 'employees/show'
  #get 'employees/new'
  #get 'employees/create'
  #get 'employees/edit'
  #get 'employees/update'
  #get 'employees/destroy'

  resources :employees

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
  class EmployeesController < ApplicationController
    def index
         @employees = Employee.all
    end

    def show 
      @employee = Employee.find(params[:id])
    end

    
    def new
         @employee = Employee.new
    end

    def create
      @employee = Employee.new(employee_params)

      if @employee.save
        redirect_to employees_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
          @employee = Employee.find(params[:id])
    end

    def update
      @employee = Employee.find(params[:id])
      if @employee.update(employee_params)
        redirect_to employees_path
      else
        render :edit, status: :unprocessable_entity
      end
    end 
    def dev
      
    end

    def destroy
      @employee = Employee.find(params[:id])
      @product.destroy

      redirect_to employees_path, status: :see_other
    end
    private
      def employee_params
        params.require(:employee).permit(:name, :email, :mobile, :address)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
        <%= form_with model: @employee do |form| %>
          <div>
            <%= form.label :Name %><br>
            <%= form.text_field :name %>
            <% employee.errors.full_messages_for(:name).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>

          <div> 
            <%= form.label :Email %><br>
            <%= form.text_area :email %><br>
            <% employee.errors.full_messages_for(:email).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>


          <div>
            <%= form.label :Mobile %><br>
            <%= form.text_area :mobile %><br>
            <% employee.errors.full_messages_for(:mobile).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>


          <div>
            <%= form.label :Address %><br>
            <%= form.text_area :address %><br>
            <% employee.errors.full_messages_for(:address).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>


          <div>
            <%= form.submit %>
          </div>
        <% end %>
</body>
</html>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>pixoatic.com</title>
</head>
<body>

<h1 style="color: green">Please Re - Enter Employee Information</h1>
<p>Hello ! Admin Please check information and Correct	</p>
<%= render "form", employee: @employee %>

</body>
</html>

app/views/employees/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>table</title>
	<style>
		table{
			border-collapse: collapse;
			width: 100%;   
		}
	th,td{
		border: 2px solid green; 
		padding: 10px;

	}
			 
	</style>
  </head>
<body>
     <div>
     	<br>
     <h1 style="color: red">Welcome Pixoatic Pvt.Ltd </h1>
	 <p style="color: black"> Thank you ! </p>
     <button><%= link_to "ADD NEW EMPLOYEE INFORMATION", new_employee_path %></button>
     </div>
	
    </br>

  <table>

  	  <tr>
		<th bgcolor="yellow">NAME</th>
		<th bgcolor="green">EMAIL</th>
		<th bgcolor="#008B8B">MOBILE</th>
		<th bgcolor="#D2691E">ADDRESS</th>
		<th bgcolor="#7CFC00">Show</th>
		
	</tr>
  	  	<% @employees.each do |employee| %>
	    <tr>
		    <td><a href="/employees/<%= employee.id %>"> <%= employee.name %></a></td>
			<td><%= employee.email %></td>
			<td><%= employee.mobile %></td>
		    <td><%= employee.address %></td>
	        <td><a href="/employees/<%= employee.id %>"><button>Show</button></td>
	        


		</tr>	
   <% end -%>
  </table>


</body>
</html>

 

app/views/employees/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>pixoatic</title>
</head>
<body>

<h1 style="color: green">Please Add New Employee</h1>
<%= render "form", employee: @employee %>

</body>
</html>

app/views/employees/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>pixoatic</title>
<style>
		table{
			border-collapse: collapse;
			width: 100%;   
		}
	th,td{
		border: 2px solid green; 
		padding: 10px;

	}
    h1{
    	text-align: center;
    }
</style>

</head>
<body>


<table border="1">
	<h1 style="color: Green" >Thank You ! Employee inforamation </h1>

	<tr>
		<th>NAME</th>
		<th>EMAIL</th>
		<th>MOBILE</th>
		<th>ADDRESS</th>

	</tr>
     <tr>
			<td><%= @employee.name %></td>
			<td><%= @employee.email %></td>
			<td><%= @employee.mobile %></td>
			<td><%= @employee.address %></td>

     </tr>

</table>
 <br>
<button onclick="history.back()">Back</button>
<button><%= link_to "Edit", edit_employee_path(@employee) %></button>
<button><%= link_to "Destroy", employee_path(@employee), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></button>

</br>
</body>
</html> 

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Company</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>